version: "3.9"
services:
  nginx:
    image: nginx:1.23.3
    container_name: give-cedar-rf-nginx
    restart: always
    networks:
      traefik:
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ${STATIC_PATH}:/www/data:ro
      - nginx:/var/log/nginx
    labels:
      - traefik.enable=true

      - traefik.http.routers.nginxGiveCedar.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.nginxGiveCedar.service=nginxGiveCedar
      - traefik.http.routers.nginxGiveCedar.entryPoints=http

      - traefik.http.routers.nginxGiveCedarHttps.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.nginxGiveCedarHttps.service=nginxGiveCedar
      - traefik.http.routers.nginxGiveCedarHttps.entryPoints=https
      - traefik.http.routers.nginxGiveCedarHttps.tls.certResolver=letsEncrypt

      - traefik.http.services.nginxGiveCedar.loadbalancer.server.port=80

networks:
  traefik:
    external: true
    name: traefik

volumes:
  nginx: